import { defineConfig, definePackage, defineState } from "../../sdk/typescript/mod.ts";

type ScopeConfig = {
  readonly blocked: readonly string[];
  readonly allowed: readonly string[];
};

type ScopeState = {
  readonly violations: readonly string[];
};

const parseConfig = (raw: unknown): ScopeConfig => {
  const record = typeof raw === "object" && raw !== null
    ? (raw as Record<string, unknown>)
    : {};
  const toStringArray = (value: unknown): readonly string[] =>
    Array.isArray(value)
      ? value.filter((v): v is string => typeof v === "string")
      : [];
  return {
    blocked: toStringArray(record.blocked),
    allowed: toStringArray(record.allowed),
  };
};

const parseState = (raw: unknown): ScopeState => {
  const record = typeof raw === "object" && raw !== null
    ? (raw as Record<string, unknown>)
    : {};
  return {
    violations: Array.isArray(record.violations)
      ? record.violations.filter((v): v is string => typeof v === "string")
      : [],
  };
};

const globMatch = (path: string, pattern: string): boolean => {
  let s = pattern.replace(/[.+^${}()|[\]\\]/g, "\\$&");
  // Replace ** patterns with placeholders to prevent glob * and ? from mangling them
  s = s.replace(/\/\*\*\//g, "\x01");  // /**/
  s = s.replace(/^\*\*\//, "\x02");    // leading **/
  s = s.replace(/\/\*\*$/, "\x03");    // trailing /**
  s = s.replace(/\*\*/g, "\x04");      // standalone **
  // Now safely replace single-char glob tokens
  s = s.replace(/\*/g, "[^/]*");
  s = s.replace(/\?/g, "[^/]");
  // Expand placeholders into regex fragments
  s = s.replace(/\x01/g, "/(.+/)?");   // /**/  -> zero or more segments
  s = s.replace(/\x02/g, "(.+/)?");    // **/   -> zero or more leading
  s = s.replace(/\x03/g, "(/.+)?");    // /**   -> zero or more trailing
  s = s.replace(/\x04/g, ".*");        // **    -> anything
  return new RegExp(`^${s}$`).test(path);
};

const matchesAny = (path: string, patterns: readonly string[]): boolean =>
  patterns.some((p) => globMatch(path, p));

const extractFilePath = (input: unknown): string | null => {
  if (typeof input !== "object" || input === null) return null;
  const record = input as Record<string, unknown>;
  const toolInput = record.tool_input;
  if (typeof toolInput !== "object" || toolInput === null) return null;
  const ti = toolInput as Record<string, unknown>;
  return typeof ti.file_path === "string" ? ti.file_path : null;
};

export default definePackage({
  config: defineConfig(parseConfig),
  state: defineState({ violations: [] }, parseState),

  sessionStart: ({ config }) => {
    const lines: string[] = ["## Scope Guard"];
    if (config.blocked.length > 0) {
      lines.push("");
      lines.push("Blocked files (do NOT edit):");
      for (const p of config.blocked) lines.push(`  - ${p}`);
    }
    if (config.allowed.length > 0) {
      lines.push("");
      lines.push("Allowed files (stay within this scope):");
      for (const p of config.allowed) lines.push(`  - ${p}`);
    }
    if (config.blocked.length === 0 && config.allowed.length === 0) {
      return null;
    }
    return lines.join("\n");
  },

  preToolUse: ({ config, input }) => {
    const filePath = extractFilePath(input);
    if (!filePath) return { decision: "allow" };

    if (config.blocked.length > 0 && matchesAny(filePath, config.blocked)) {
      return {
        decision: "block",
        reason: `scope-guard: ${filePath} matches a blocked pattern. Do not edit this file.`,
      };
    }

    return { decision: "allow" };
  },

  stop: async ({ config, state, env }) => {
    if (config.allowed.length === 0) {
      return { decision: "done" };
    }

    // Read files_touched from kernel state
    let filesTouched: readonly string[] = [];
    try {
      const kernelPath = `${env.stateDir}/kernel.json`;
      const kernelText = await Deno.readTextFile(kernelPath);
      const kernel = JSON.parse(kernelText) as Record<string, unknown>;
      if (Array.isArray(kernel.files_touched)) {
        filesTouched = kernel.files_touched.filter(
          (f): f is string => typeof f === "string",
        );
      }
    } catch {
      return { decision: "done" };
    }

    const outOfScope = filesTouched.filter(
      (f) => !matchesAny(f, config.allowed),
    );

    if (outOfScope.length === 0) {
      await state.set({ violations: [] });
      return { decision: "done", feedback: "scope-guard: all edits within scope." };
    }

    await state.set({ violations: outOfScope });
    const list = outOfScope.map((f) => `  - ${f}`).join("\n");
    return {
      decision: "continue",
      feedback: `scope-guard: ${outOfScope.length} file(s) outside allowed scope:\n${list}\nRevert these changes or move the logic into allowed files.`,
    };
  },
});
